---
jobs:
- name: "global"
  connections:
  - url: 'jdbc:postgresql://db/postgres'
    username: 'postgres'
    password: 'example'
  queries:
  - name: "db_users"
    help: "Database Users"
    values:
      - "count"
    query:  |
            select count(1) count from pg_catalog.pg_user