---
jobs:
- name: "global"
  connections:
  - url: 'jdbc:mysql://db/mysql'
    username: 'root'
    password: 'example'
  queries:
  - name: "db_users"
    help: "Database Users"
    values:
      - "count"
    query:  |
            SELECT count(User) count FROM mysql.user