version: '3.1'
services:
  prometheus:
    build: prometheus
    ports:
      - 9090:9090
  exporter:
    build: .
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: test
