version: '3.1'
services:
  prometheus:
    build: prometheus
    ports:
      - 9090:9090
  exporter:
    build: .
    ports:
      - 5555:5555
  db:
    image: oracle/database:12.2.0.1-ee
    ports:
      - 1521:1521
